### ISSUE TITLE
Scheduler unavailable exception

### ISSUE THREAD

**Issue by lebannen** [reactor/reactor-addons#114]
I have a question about ExecutorServiceScheduler. 
When it fails to schedule task, RejectedExecutionException with all its stacktrace is swallowed, and schedule returns REJECTED disposable. The result of this call is checked and if it equals REJECTED then new RejectedExecutionException is thrown. But this exception does not have stacktrace of the first one. So I see only StepVerifier calls in stacktrace, and it's quite difficult to find out the root cause of the problem.
What was the reason of such decision?

**Comment by lebannen** [comment]
In addition to this question, I've found strange behaviour.

`ExecutorService executor = Executors.newSingleThreadExecutor();
        Scheduler scheduler = Schedulers.fromExecutor(executor);

        DirectProcessor<Integer> processor = DirectProcessor.create();

        Flux<Integer> flux = processor
                .publishOn(scheduler)
                .window(Duration.ofMillis(400))
                .map(x -> 5)
                .doFinally(signalType -> executor.shutdown());


        for (int i = 0; i < 10; i++) {
            int p = i;
            timeScheduler.schedule(() -> processor.onNext(2 * p + 1), 100 * p + 4000, TimeUnit.MILLISECONDS);
        }

        StepVerifier.create(flux)
                .then(() -> timeScheduler.advanceTimeBy(Duration.ofMillis(5000)))
                .expectNext(3)
                .thenCancel()
                .verify();`


This test fails with RejectedExecutionException also it fails with AssertionError without `.publishOn(scheduler)` or `.doFinally(signalType -> executor.shutdown())`. 

I understand that using Flux.window() this way is very awkward, but it looks like there is some problem with disposing flux with such setup (publishOn + executor shutdown), because FluxWindowBoundary.dispose() is not called in this case. When I remove publishOn, I receive AssertionError and FluxWindowBoundary.dispose() is called.

**Comment by smaldini** [comment]
It does seem to be connected to https://github.com/reactor/reactor-core/issues/347 if we can centralize that discussion here.

**Comment by lebannen** [comment]
This issue is probably connected to the first part of my problem. publishOn throws RejectedExecutionException correctly for my case, but with wrong stacktrace. This is caused by a lot code like this:
`if (trySchedule() == Scheduler.REJECTED) {
				throw Operators.onRejectedExecution(this, null, t);
			}`

in `FluxPublishOn` class.

But the second part of my problem is in wrong behaviour of StepVerifier probably. It cancels Flux, but it does not cancel DirectProcessor.

**Comment by smaldini** [comment]
Should now be fixed on reactor-core master
