### ISSUE TITLE
Java 9 - tools.jar dependency

### ISSUE THREAD

**Issue by orlok1** [reactor/reactor-addons#124]
My project uses io.projectreactor.addons - reactor-logback.  This in turn is depending on the OpenHFT Chronicle project, which in turn depends on OpenHFT lang.jar....which in turn is depending on 'tools.jar' which has been removed in Java 9.
Any advice on how to get round this dependency issue, or will there be a release resolving this issue.

**Comment by simonbasle** [comment]
@orlok1 unfortunately looks like we'll have to wait for your other issue (OpenHFT/Java-Lang#83) to be resolved ⏳

**Comment by simonbasle** [comment]
@orlok1 don't hesitate to fork, bump the dependency, test and submit a PR if you notice OpenHFT doing a release before we do ;)

**Comment by blabadi** [comment]
I'm using JDK 11, I tried excluding the tools jar: 
```
        <dependency>
            <groupId>io.projectreactor.addons</groupId>
            <artifactId>reactor-logback</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.java</groupId>
                    <artifactId>tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

it seems to remove the maven build error, and logger is working fine in terms that it actually initializes and writes to log files normally:

```
17:33:27,683 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [reactor.logback.AsyncAppender]
17:33:27,683 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [async]
17:33:27,683 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to reactor.logback.AsyncAppender@7b15d23c
17:33:27,706 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [reactor.logback.AsyncAppender]
17:33:27,706 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [asyncFailureLog]
17:33:27,706 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [failureLogAppender] to reactor.logback.AsyncAppender@33d455d6
```

it maybe that the classes are resolved in some other way at runtime or it just haven't tried to load them yet and will fail later on.

**Comment by simonbasle** [comment]
I'm wondering if it makes sense to keep the `reactor-logback` artifact at all. @blabadi have you looked into https://github.com/OpenHFT/Chronicle-Logger ? This could prove a better alternative (as we don't necessarily have the bandwidth to maintain a logger on top of ChronicleQueue ourselves, and it makes better sense to rely on an official project).

**Comment by blabadi** [comment]
@simonbasle  no, but reading the readme, they say : 

> At the moment, Chronicle Logger only supports binary logs, which is beneficial for write speed but requires extra tools to read them. We provide some basic #tools[tools] for that and an API to develop your own.

as I understand from this that the log file will be a binary file instead of text file which doesn't work/unnecessary in my case.

on another note, I'm a bit confused why reactor needed to use an external events queue for reactor, doesn't reactor have a built-in mechanism to manage I/O events ?

**Comment by simonbasle** [comment]
that's for the `DurableLoggerAppender`, which was an attempt to use OpenHFT/Chronicle-Queue as a mecanism to directly write to a log file, but fast.

`AsyncAppender` uses a reactor `Processor` to queue up logging events and consume them from a separate thread into a delegate Appender, but it hasn't been really maintained.

We are now considering sunsetting both of these, as `Chronicle-Logger` is likely a better replacement for `DurableLoggerAppender`, while I'm not sure there's huge value in `AsyncAppender` compared to the logging libraries own async appenders.
