### ISSUE TITLE
Key-Value caching support 

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-addons#130]
# Proposal - Add caching support on the key-value basis 

I see the need (the similar question was asked to @simonbasle and me on the recent JavaDayUA) to provide some additional caching abstraction in Reactor. This feature will provide additional caching mechanisms which will be based on extracted keys from the upstream data. In the case of key presence in the corresponding Cache supported storage (like caffeine) the operator will decide to pass data to the downstream and execute, let's say, long-running job or alternatively, just to get the value from the storage and pass it to the final subscriber. In that case, the whole pipe may be stateless and take a few parameters for its needs: 

``` Java
LoadingCache<Integer, SomeMongoResponse> graphs = Caffeine.newBuilder()
    .maximumSize(10_000)
    .expireAfterWrite(5, TimeUnit.MINUTES)
    .refreshAfterWrite(1, TimeUnit.MINUTES)
    .build(key -> createExpensiveGraph(key));

Cache
   .from(Flux.just(1,2,3,4,5,6))
   .with(graphs.asMap())                                     //  (1) 
   .keyExtractor(Function.identity())                  //  (2)
   .apply(someLongrunningMongoRequest)     //  (3)
   .map(...)
   .transform(..)
   .subscribe();
```

In this example, we provided the first variable `graphs` which may be a stateful field used for the cache purpose. The second part, which represents fluent API of possible Cache operator for that purpose, just wraps upstream of keys. In the point `(1)` we pass the map which will be used as a cache storage, so it will be the responsibility of the user to choose corresponding cache provider, etc. And after that, we pass key extractor and finalize initialization with `apply` to downstream (point `(3)`). 
So, finally, we will get the next pipe 
![cacheoperator](https://user-images.githubusercontent.com/5380167/32511611-f925f1ae-c3fc-11e7-8370-0a71b0b2e38c.png)

Also, I strongly believe that this operator will be very useful in Spring 5 itself since (as far as I know) there was no support for caching with reactive types

**Comment by OlegDokuka** [comment]
If this proposal will be useful, I will provide a corresponding PR in a few days

**Comment by smaldini** [comment]
Its a pretty interesting addition and a kotlin extension can add it up on top of Flux as we do with other extra addons :) I'd need to see some test cases to explore a bit more.

**Comment by OlegDokuka** [comment]
Great to hear that. I will provide you with a few test cases soon :)

**Comment by nebhale** [comment]
I would call this super interesting to the Java Client project.  We wouldn't need something quite as full-featured as caching product (a `Map` would be good enough for most of our purposes) but something that allowed us to describe a `computeIfEmpty()` kind of thing would make sense for things like OAuth tokens, etc.  I know that the Boot team was dealing with this same kind of issue when handling OAuth token keys.

**Comment by OlegDokuka** [comment]
@nebhale It would be amazing if proposed API would be useful for you. Currently, I am planing to rely on the simple and than adjust features step by step.

**Comment by simonbasle** [comment]
(note: lots of interesting discussions in the PR: #131)

@nebhale wouldn't a simplistic roll-your-own `Map<String, Mono<?>>` with `mono.cache(Duration)` in that case? ie. do you really miss Reactor specific code to achieve that, or could you already do everything you need with a `Map` / caching library + `Mono#cache` variants?
(if not, please chime in the PR 😉)

**Comment by nebhale** [comment]
@simonbasle Yes, I do already implement this on my own using a `Map`, but given the size and complexity of the code, it’s not very clear that it’s what I’m doing.  In fact, it took me 10 minutes to work out that I was implementing this use case, even though I _wrote_ that code.  The difference between the roll-your-own and `.cache(Function<T, U> keyExtractor, Function<T, V> computeIfEmpty())` from a “clarity of meaning” point of view is pretty large in my opinion.
