### ISSUE TITLE
Reset after retry recovery?

### ISSUE THREAD

**Issue by nahguam** [reactor/reactor-addons#140]
Hi,

Is it possible to get the `DefaultRetry` to reset its backoff (`DefaultContext`) after a successful recovery (`onNext` invoked after successful resubscribe)?

**Comment by simonbasle** [comment]
unfortunately no, the `retryWhen` operator doesn't do anything in particular on `onNext`, nor could it notify the `DefaultRetry`, which it simply sees as a `Function`.
