### ISSUE TITLE
retryExponentialBackoff on a Mono returns a Flux

### ISSUE THREAD

**Issue by bjartek** [reactor/reactor-addons#151]
Example: https://github.com/bjartek/webflux-retry/blob/master/src/main/kotlin/org/bjartek/webfluxretry/WebfluxRetryApplication.kt

Should it not return a Mono?

**Comment by simonbasle** [comment]
mmh yes, the extension method uses the apply method from the Retry Java class, but it isn't well adapted to a Mono, as it converts to a Flux first. the extension method could be amended to directly call Mono.retryWhen

**Comment by bjartek** [comment]
Can we close this then? Or do you prefer to have them open until they are released?

**Comment by simonbasle** [comment]
we can close, forgot to reference the issue in the commit (which we usually use to auto close)
