### ISSUE TITLE
Translate AccessEvent to reactor context

### ISSUE THREAD

**Issue by jmcshane** [reactor/reactor-addons#156]
This class in the logback context only works within Servlet environments: https://logback.qos.ch/apidocs/ch/qos/logback/access/spi/AccessEvent.html. What do you think about adding a ReactiveAccessEvent that corresponds to the IAccessEvent interface? If you think this would be good in this library, I can help develop.

**Comment by simonbasle** [comment]
It seems to be dependent on the servlet API (references `javax.servlet.http.HttpServletRequest` and `javax.servlet.http.HttpServletResponse`), not sure where such a class would best live.

**Comment by jmcshane** [comment]
Hmm, yeah, I realize that IAccessEvent wouldn't work in that context. I'm trying to work on doing access logging in Netty similar to the [LogbackValve](https://github.com/qos-ch/logback/blob/master/logback-access/src/main/java/ch/qos/logback/access/tomcat/LogbackValve.java) in Tomcat. Any thoughts on how this might be implemented in general? I've got the call `Mono<Void>` object logging successfully after the response is committed, but I'm just writing my own domain object right now that does the translation from the `ServerWebExchage` object in spring-webflux to some sort of logging event.

Does that use case make sense?

**Comment by simonbasle** [comment]
Looks like in the Scala world, there's an adapter for Play Framework that plainly ignores the servlet dimension: https://github.com/cardamo/play-logback-access/blob/master/src/main/scala/adapter.scala#L22

I also found [logback-access-spring-boot-starter](https://github.com/akihyro/logback-access-spring-boot-starter), which has been upgraded for Spring Boot 2 but so far only with support for the Tomcat, Jetty and Undertow flavors. I think that would be a good umbrella for what you're looking to achieve.
