### ISSUE TITLE
RetryExhaustedException does not extend ReactorException

### ISSUE THREAD

**Issue by vooft** [reactor/reactor-addons#157]
RetryExhaustedException extends only RuntimeException, so reactor.core.Exceptions#unwrap can not be used with it and it has to be handled separately.

**Comment by OlegDokuka** [comment]
Hi @vooft, what do you mean by `handled separately`. Could you please show your use-case

**Comment by OlegDokuka** [comment]
Ok, now I see that, will fix quickly. Thanks!
