### ISSUE TITLE
Memory leak with reactor-logback by using reactor.logback.AsyncAppender to log into separate file

### ISSUE THREAD

**Issue by georgmittendorfer** [reactor/reactor-addons#168]
Today I tracked down a memory leak in my application.

It is a Spring Webflux application. Before creating the Mono that I return via the RestController I log parts of the request (called 'command' in my domain) into a separate log file. If I do this every command passed to the logger does not get released.

Code for logging:

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

[...]

@RestController
public class MyApiHandler {

[...]

private final Logger commandLogger = LoggerFactory.getLogger("commands");

[...]

@PostMapping(value = "/", consumes = MediaType.APPLICATION_JSON_VALUE)
public Mono<ResponseEntity<String>> exchange(@Valid @RequestBody MyCommand command, ServerHttpRequest request) {

[...]

commandLogger.info("IP [{}] Command [{}] Details [{}] Id [{}]", ip, command.getCommand(), command, command.getSessionId());

[...]

Mono<ResponseEntity<String>> responseEntityMono = executeCommand(command)...

```

My log configuration looks like this (slf4j with logback):

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

  <include resource="org/springframework/boot/logging/logback/defaults.xml" />
  <property name="LOG_FILE" value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}/spring.log}"/>
  <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
  <include resource="org/springframework/boot/logging/logback/file-appender.xml" />

  <springProperty scope="context" name="commandsLogFile" source="my.log.file" defaultValue="my-commands.log"/>
  <springProperty scope="context" name="commandsLogPattern" source="my.log.pattern" defaultValue="%d{yyyy-MM-dd HH:mm:ss.SSS} %msg%n%nopex"/>
  <appender name="COMMANDS" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <encoder>
      <pattern>${commandsLogPattern}</pattern>
    </encoder>
    <file>${commandsLogFile}</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
      <fileNamePattern>${commandsLogFile}.%d{yyyy-MM-dd}.%i.gz</fileNamePattern>
      <maxFileSize>${LOG_FILE_MAX_SIZE:-10MB}</maxFileSize>
      <maxHistory>${LOG_FILE_MAX_HISTORY:-0}</maxHistory>
    </rollingPolicy>
  </appender>

  <!-- Wrap calls to the file logger with async dispatching to Disruptor. -->
  <appender name="asyncFile" class="reactor.logback.AsyncAppender">
    <appender-ref ref="FILE"/>
  </appender>

  <!-- Wrap calls to the console logger with async dispatching to Disruptor. -->
  <appender name="asyncConsole" class="reactor.logback.AsyncAppender">
    <appender-ref ref="CONSOLE"/>
  </appender>

  <!-- the following memory leaks if appender get's referenced from commands logger. -->
  <appender name="asyncCommands" class="reactor.logback.AsyncAppender">
    <appender-ref ref="COMMANDS"/>
  </appender>
  <logger name="commands" level="INFO" additivity="false">
    <appender-ref ref="asyncCommands" />
  </logger>

  <logger name="my.stuff" level="INFO"/>
  <logger name="reactor.Mono" level="DEBUG"/>
  <logger name="reactor.Flux" level="DEBUG"/>
  <logger name="org.springframework.web" level="WARN"/>

  <root level="WARN">
    <appender-ref ref="asyncFile"/>
    <appender-ref ref="asyncConsole"/>
  </root>

</configuration>
```
I am using slf4j 1.7.25, reactor logback-3.1.7.RELEASE, spring-cloud version Finchley.SR1 and project reactor version Bismuth-SR11.

Only the references passed to the commands logger cause the memory leak. All other logging seems to be working properly.

By commenting out the log call or by not using the asyncCommands appender but using `<appender-ref ref="COMMANDS"/>` directly for the `commands` logger the memory leak is gone.

As the solution was to avoid using the reactor.logback.AsyncAppender I decided to open the issue here but the root cause might be somewhere else. Please inform me how to proceed in this case. I can provider further information if you want me to.

**Comment by mahanhz** [comment]
We experienced the same issue in our Spring Webflux application.

We noticed that the heap was continuously increasing after each GC until it filled up causing constant full GC with pauses up to 2 seconds.

We took a heapdump and a couple of profilers suggested that the issue was potentially with **reactor.core.publisher.WorkQueueProcessor** which was being called by **reactor.logback. AsyncAppender**.

I then came across this issue at which point I updated our logback-spring.xml file to replace all instances of reactor.logback.AsyncAppender with ch.qos.logback.classic.AsyncAppender.

The heap now looks fine.

**Comment by To-da** [comment]
There was EOL of reactor-logback addons for 3.3: https://github.com/reactor/reactor-addons/commit/d3e5029c369576dc9245a1883e7df4afc4b4e775
@smaldini What is recommended async Adapter alternative for Logback in high-throughput application (with expectation of minimal latency)? Is it only logback AsyncAppender?

**Comment by simonbasle** [comment]
we now recommend using relevant high performance appenders from more logging-dedicated exernal projects, off-the-shelf logback's own `AsyncAppender`
