### ISSUE TITLE
OSGI bundle

### ISSUE THREAD

**Issue by agjini** [reactor/reactor-addons#179]
# Actual behavior
Today reactor-addons artifacts `reactor-extras` and `reactor-adapter` are not valid OSGI bundle since their jar MANIFEST do not contain required OSGI bundle entries.

This will avoid to use them in OSGI application.

# Proposition

## 1: add osgi MANIFEST entries

As it is done in `reactor-core` gradle build file, you could apply `osgi` plugin to add the standard OSGI entries to the MANIFEST.MF.

This will add :
- Bundle-SymbolicName
- Implementation-Version
- Import-Package
- Export-Package
- Bundle-Version
- Bundle-Name
...

and this will make a valid OSGI bundle.

## 2: manually modify the import packages

A final step has to be done to manually declare optional dependencies as optional in `Import-Package` entry.

(to avoid to having to import it if it is not used)

**I'll start a Pull Request for this**

Thanks for your help

**Comment by agjini** [comment]
Here my Pull Request

[#180](https://github.com/reactor/reactor-addons/pull/180)

I've tested it successfully in my own project

**Comment by frankbenoit** [comment]
Please see also https://github.com/reactor/reactor-core/issues/1662  
The attribs for the source bundle should be set as well.

**Comment by simonbasle** [comment]
@frankbenoit no, I don't think we will be adding attributes to the sources jar.
