### ISSUE TITLE
'onCacheMissResume' stores everything into cache

### ISSUE THREAD

**Issue by cybuch** [reactor/reactor-addons#181]
I use caffeine AsyncLoadingCache and on async reload if I return empty mono with signature Mono<Signal<MyType>> it's not stored into cache. However I use it with CacheMono just like the example from documentation

```
CacheMono.lookup(cache.synchronous().asMap(), request)
                .onCacheMissResume { someMono(request) }
```

and there's a problem. Everything returned from `someMono` is cached - empty signal, error signal and so on. Have you thought about not storing errors in cache?

**Comment by simonbasle** [comment]
superseded by #237
