### ISSUE TITLE
Add support to sum Flux<BigDecimal> and Flux<BigInteger>

### ISSUE THREAD

**Issue by jabrena** [reactor/reactor-addons#211]
Hi,

I was reviewing the documentation for `MathFlux` but I didn´t find any method to sum a flux of BigDecimal and BigInteger.
https://projectreactor.io/docs/extra/release/api/reactor/math/MathFlux.html

I will add an example to review the concept:

``` java
    @Test
    public void SumBigIntegerTest() {

        Mono<Long> longSum = MathFlux.sumLong(Flux.just(1L, 2L, 3L));

        List<BigInteger> list = Arrays.asList(
                new BigInteger("1"),
                new BigInteger("2"),
                new BigInteger("3")
        );

        BigInteger bigIntegerSum = list.stream().reduce(BigInteger.ZERO, BigInteger::add);

        assertThat(longSum.block()).isEqualTo(bigIntegerSum.longValue());

        Flux<BigInteger> sequence = Flux.fromIterable(list);

        //Doesn´t exist the method
        //MathFlux.sumBigInteger(sequence);
    }
```

Many thanks in advance

Juan Antonio

---

**PR Development:**

- [ ] sumBigDecimal
- [ ] averageBigDecimal
- [ ] sumBigInteger

**Comment by simonbasle** [comment]
That could make sense for `MathFlux`, yeah. Would you like to mirror what is done for `sumDouble`,`averageDouble` and `sumLong` methods, and offer a PR? (ie `sumBigDecimal`, `averageBigDecimal` and `sumBigInteger`)

**Comment by jabrena** [comment]
Hi @simonbasle, I will do it.

Juan Antonio
