### ISSUE TITLE
Add missing expectations from AssertSubscriber (expectFused...)

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-addons#23]

**Comment by sdeleuze** [comment]
After porting the lite Rx API Hands-On to `ScriptedSubscriber`, I figured out that not all variants are needed because they don't work the same way. I will try to give more insight later.

**Comment by smaldini** [comment]
Last symmetric support use-case ported (finite negative) https://github.com/reactor/reactor-addons/commit/c6340ad88a39aaec5013965c5186c77578c6c729
