### ISSUE TITLE
reactor.retry.Retry does not provide methods for Mono.retryWhen(Retry retrySpec)

### ISSUE THREAD

**Issue by fabian-froehlich** [reactor/reactor-addons#231]
Since reactor version 3.3.4.RELEASE the method
`Mono.retryWhen(Function<Flux<Throwable>, ? extends Publisher<?>> whenFactory)` is deprecated.
The alternative to use Mono.retryWhen(Retry retrySpec) expects a `reactor.util.retry.Retry`. So former implementations with `reactor.retry.Retry` do not work here.

In my case I want to use a condition retry on a webclient:
```
Mono<ServiceDescription> serviceDescription = this.webClient.get().uri(uri).retrieve()
  .bodyToMono(ServiceDescription.class)
  .retryWhen(Retry.allBut(WebClientResponseException.NotFound.class).retryMax(7)
    .exponentialBackoffWithJitter(Duration.ofSeconds(1), Duration.ofSeconds(300))
    .doOnRetry(context -> LOGGER.debug("Retry: {} on {}", context.iteration(), uri, context.exception())));
```

Is this still possible to archive without using the deprecated method `Mono.retryWhen(Function<Flux<Throwable>, ? extends Publisher<?>> whenFactory)`?

**Comment by MrFix93** [comment]
We run into the same problem. In addition, I can't find why this function is deprecated? What alternative method is provided to accomplish this?

**Comment by fabian-froehlich** [comment]
As mentioned in the release notes of [3.3.4.RELEASE](https://github.com/reactor/reactor-core/releases/tag/v3.3.4.RELEASE) there should be a way to filter the retry based on errors.
It states:

> The API is build around the Retry abstract class, with two builders (or Spec) to fluently configure the retries
> This allows us to introduce additional new features:
> all variants support a filter for errors to be retried

So maybe one would archive the same with the following code:
```
 .retryWhen(Retry.backoff(7, Duration.ofSeconds(1))
  .maxBackoff(Duration.ofSeconds(300))
  .filter(e -> e.getClass() != WebClientResponseException.NotFound.class));
```

Still, the method `Retry.allBut(...)` looks cleaner to me and is often explained when googling or browsing stackoverflow.

**Comment by PostIt59** [comment]
Still facing the issue. @fabian-froehlich have you found an other solution than using `Retry.allBut` because in my case I want to retry only if there is a `ConnectTimeoutException` :/

**Comment by fabian-froehlich** [comment]
> Still facing the issue. @fabian-froehlich have you found an other solution than using `Retry.allBut` because in my case I want to retry only if there is a `ConnectTimeoutException` :/

What is wrong with my solution, using a filter?

**Comment by PostIt59** [comment]
> > Still facing the issue. @fabian-froehlich have you found an other solution than using `Retry.allBut` because in my case I want to retry only if there is a `ConnectTimeoutException` :/
> 
> What is wrong with my solution, using a filter?

Sorry, it's clearly a good solution. Probably too exhausted when I read your answer 😄 . Thks for the tip ;)

**Comment by simonbasle** [comment]
as of `3.3.9.RELEASE` there is a (reactor-core)`Retry`.`withThrowable` that can convert a reactor-extra `retry.Retry` to a reactor-core `Retry`.
