### ISSUE TITLE
CacheMono - Calls doOnCancel

### ISSUE THREAD

**Issue by winster** [reactor/reactor-addons#236]
I use CacheMono and Caffeine in a usecase where I want to cache the webservice response to avoid redundant requests. When lookup fails, a webservice call will be made and response will be populated in cache against the key/request.

The problem I see is, during the first time, after the webclient is invoked and before `andWriteWith` is invoked, the mono gets cancelled and `doOnCancel` is invoked. But client response is properly captured and cache is populated. 
Why is this behaviour?
For reference, I created a gist. [here](https://gist.github.com/winster/19e11fc9baf3784b71e48ad56fbbac73)

ps: I have noticed a similar situation (outside cachemono context) when I used `retryWhen`. After the retries, the mono is cancelled.

**Comment by winster** [comment]
I can give a relatively simpler code to test.

```
        Map<String, String> cache = new HashMap<>();
        Mono<String> fetchDataMono = Mono.just("Test").doOnCancel(() -> log.info("doOnCancel")).doOnSuccess(s -> log.info("doOnSuccess"));
        Mono<String> cacheMono = CacheMono
            .lookup(key -> Mono.justOrEmpty(cache.get(key))
                               .map(Signal::next),
                "1")
            .onCacheMissResume(() -> fetchDataMono)
            .andWriteWith((key, signal) -> Mono.empty());
        cacheMono.subscribe();
        
```
the output is as follows
```
doOnSuccess
doOnCancel
```

I came across 2 related issues. https://github.com/reactor/reactor-netty/issues/741 & https://github.com/spring-projects/spring-framework/issues/22952
But both are closed and I use the latest versions of libraries.

**Comment by ben-manes** [comment]
Note that I'm not very familiar with Reactor and the benefits of `CacheMono`...

You might consider letting Caffeine do the memoization through an `AsyncCache`, and convert between `CompleteableFuture` and `Mono`. The cache will automatically discard the future if it does not succeed with a non-null value. By deferring to the cache you avoid a get-load-put race where stampede of callers causes redundant work to be performed.

```java
AsyncCache<String, String> cache = ...
var future = cache.get(key, (k, executor) -> {
  Mono result = ...
  return result.toFuture();
});
return Mono.fromFuture(future);
```

The cache will block only when the entry is absent and only long enough to insert the in-flight future into the map. This gives you a bounded `ConcurrentHashMap<K, CompletableFuture<V>>`, which can easily to adapted to/from Mono.

**Comment by winster** [comment]
@ben-manes what do you think about my second example. The problem is not with usage of any cache rather with CacheMono and calling `cancel` unnecessarily.

**Comment by simonbasle** [comment]
I looked at the reproducer and it appears the `cancel()` is triggered by `CacheMono`'s internal use of `Mono.materialize()`. Maybe that can be avoided in core's `MonoMaterialize.java`.

That said, given how little time we manage to spend on maintaining `CacheMono` and `CacheFlux` and given the input from @ben-manes (with potential stampede, etc..), I wonder if we shouldn't entirely deprecate this whole (mediocre) attempt at a cache-to-reactive helper.

**Comment by simonbasle** [comment]
@winster please note not all cancellation are a bug and can be avoided, and not all cases are related. Here this is a very specific issue with `Mono.materialize`, I'd say.
