### ISSUE TITLE
Guava's ListenableFuture to Mono/Flux adapter

### ISSUE THREAD

**Issue by kevinten10** [reactor/reactor-addons#248]
How about `Guava`'s [ListenableFuture](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/ListenableFuture.java) adapter?

See #41.

Looking forward to your reply.

**Comment by simonbasle** [comment]
Hi @kevinten10 thanks for the suggestion.
We don't really intend to add much to `reactor-adapter` now, it is intended as primarily helping integration with three other Reactive Streams implementations of note, RxJava 2 & 3 and Akka Streams (to a lesser extent).
We're not considering adding wrapper and adapters for various non-reactive types at this point (reactive as in _reactive streams_), especially when these can be easily adapted via `Mono.create` for example.

**Comment by kevinten10** [comment]
I understand and agree.

But for most historical systems and frameworks, they do rely on non-reactive implementations.

I have to use `Mono.create` in every project to adapt them.

If we can provide a more general adapter, I think this is a good way.

Thank you for your reply.
