### ISSUE TITLE
reactor.retry.Retry is incompatible with the reactor-core reactor.util.retry

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-addons#249]
Tried to use reactor-core 3.4.2 and reactor-extra 3.4.2 from Maven repo. The types are incompatible, all retry code that was using extra does not compile.

**Comment by simonbasle** [comment]
there is a migration path in reactor-core: `Retry.withThrowable(Function<Flux<Throwable>, Publisher>)` (addons' `Retry` is such a `Function`).
