### ISSUE TITLE
pom is empty since split of publications for the gha release

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-addons#254]
Since the modifications made to introduce release workflow, the `pom.xml` is empty.
We need to double-check with older snapshots if anything else is missing.
This is probably linked to the two Gradle publications and how artifactory resolves them.

**Comment by simonbasle** [comment]
after having investigated potentials fixes and verified that no other file is problematic with the current build process, it appears we have two choices:
 1. publish the extra artifacts to Maven Central (addons isn't directly concerned, but `docsZip` task in reactor-core comes to mind)
 2. implement a convoluted solution to have different set of artifacts deployed to Artifactory vs Maven Central

1) was suggested by @mp911de who does that for Lettuce. It wasn't explored earlier because we were under the impression Maven Central would reject a zip outright (since Artifactory-to-Bintray step would reject it. so this was probably a limitation imposed by bintray rather than one for the benefit of Maven Central?)

2) is convoluted but boils down to disabling pom and module generation tasks for the extra publication and triggering a copy of the `mavenJava` publication's own pom into the folder of the extra publication, so that `artifactoryPublish` (and `extractBuildInfo`) can find it. The root cause for the empty pom is still unclear, because it appears there is some amount of randomness to it. (ie we have snaphots with empty poms then snapshots with correct pom). It seems to be related to the fact that any `MavenPublication` implicitly generates a pom and that the extra's pom (empty) would somehow replace the mavenJava pom (full) _but not all the time_.

**Comment by simonbasle** [comment]
this is the sort of hoops solution 2 would make us jump through:

```groovy
//this seems to be key in avoiding pom.xml overwrites while still allowing publishAllPublicationsToXxxRepository
tasks.all {
	if (it.name.contains("ArtifactoryOnlyPublication")) {
		println "disabling $it.name"
		enabled = false
	}
}

task copyPom(type: Copy) {
	dependsOn tasks.withType(GenerateMavenPom).matching {
		it.name.contains("MavenJava")
	}
	from "$buildDir/publications/mavenJava/pom-default.xml"
	into "$buildDir/publications/artifactoryOnly/"
}

if (rootProject.hasProperty("artifactory_publish_password")) {
	apply plugin: "com.jfrog.artifactory"

	afterEvaluate {
		tasks.getByName("extractModuleInfo").dependsOn(tasks.copyPom)
	}

    //...
}
```

**Comment by simonbasle** [comment]
we'll be implementing solution 1 and publish the extra artifacts (docsZip, etc...) for the time being.

**Comment by mp911de** [comment]
FTR: https://repo1.maven.org/maven2/io/lettuce/lettuce-core/6.1.0.RELEASE/lettuce-core-6.1.0.RELEASE-docs.zip
