### ISSUE TITLE
RxJava3Adaptor.monoToSingle causes inconsistent behavior in IntegrationTest and real-world test

### ISSUE THREAD

**Issue by kanesee** [reactor/reactor-addons#257]
I'm unable to get the Principal from ServerWebExchange when it's wrapped with `RxJava3Adaptor.monoToSingle`

## Expected Behavior
Returns Principal's name in example below

## Actual Behavior
Returns "no principal" in example below

## Steps to Reproduce

Here's a simple example

    import reactor.adapter.rxjava.RxJava3Adapter;
    import reactor.core.publisher.Mono;
    import io.reactivex.rxjava3.core.Single;

    @RestController
    @RequestMapping("/test")
    public class MyController {

      @GetMapping("/mono")
      public Mono<String> getMono(ServerWebExchange exchange) {
        return exchange.getPrincipal()
          .map(principal -> principal.getName())
          .switchIfEmpty(Mono.just("no principal"));
      }

      @GetMapping("/single")
      public Single<String> getSingle(ServerWebExchange exchange) {
        return RxJava3Adapter.monoToSingle(exchange.getPrincipal()
          .map(principal -> principal.getName())
          .switchIfEmpty(Mono.just("no principal")));
      }

    }

Hitting `/test/mono` returns the Principal name every time.
Hitting 'test/single` using curl returns "no principal". However, in IntegrationTest, it returns the Principal name.

Here's sample curl command (that fails every time, ie, returns "no principal")

    curl --request GET \
    --url http://localhost:8080/test/single \
    --header 'authorization: Bearer XXXX' \

Here's example Integration test (that succeeds, ie, doesn't return "no principal")

    @WithMockUser
    @ExtendWith(SpringExtension.class)
    @SpringBootTest(webEnvironment = WebEnvironment.MOCK)
    @AutoConfigureWebTestClient
    public class IntegrationTest {

      @Autowired
      private WebTestClient webClient;

      @Test
      void testPrincipal() {
        final EntityExchangeResult<byte[]> getResult =
            webClient
                .get()
                .uri("/test/single")
                .exchange()
                .expectStatus()
                .isOk()
                .expectBody()
                .returnResult();

        final String response = new String(getResult.getResponseBody());
        assertNotEquals(response, "no principal");
      }

## Your Environment

* io.projectreactor:reactor-core:3.4.5
* io.projectreactor.netty:reactor-netty-http
* JVM version (`java -version`): OpenJDK Runtime Environment (build 15.0.1+9)
* OS and version (eg `uname -a`): Darwin MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**Comment by kanesee** [comment]
Please disregard the integration test results I mentioned. It was always passing because of that special @WithMockUser. If I remove it and send an authorization header, it fails on the `/test/single` endpoint same as curl.

Attaching runnable code to show the issue
[RxBridgeBug.zip](https://github.com/reactor/reactor-addons/files/6388460/RxBridgeBug.zip)

**Comment by kanesee** [comment]
Not sure if this is related, but when I was tracing through the code, I found this method in [ReactiveAdapterRegistry](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/ReactiveAdapterRegistry.java#L139-L147).

Seems if reactor is present, then the reactiveadapter is never added. Not sure if that is affecting me.

I assumed it's permitted to have both RxJava and Reactor in the same project otherwise there wouldn't exist a RxJava3Adapter

**Comment by kanesee** [comment]
I traced through the code and one thing I noticed is that the Reactor Context seems to be used. In the `Mono` case, it holds a `SecurityContext` which provides the Authenticated `Principal`. In the `Single` case, the Reactor Context is empty.

I suspect the bridge is not copying the Reactor Context's state because RxJava has no concept of a Context.

**Comment by simonbasle** [comment]
Yes, unfortunately RxJava has no concept of a `Context`, so sticking an RxJava subchain breaks the access to `Context`ual data, which includes `SecurityContext`... One way around that is to explicitly wrap RxJava publishers in a Reactor `flatMap` or `deferContextual` Flux/Mono.
