### ISSUE TITLE
Move reactor.swing.SwtScheduler.java to reactor.swt.SwtScheduler.java

### ISSUE THREAD

**Issue by vogella** [reactor/reactor-addons#268]
I was confused to find the SwtScheduler in the swing package. Could this moved to its own package? You could keep the old class and extend the new one an deprecate it to keep compatibility.

I can provide PR if you agree that this is a good idea.

**Comment by simonbasle** [comment]
Hey @vogella, yeah this package doesn't make much sense.

But beyond that, I'm not sure the `SwtScheduler` is that useful at all.
We'd like to remove `SwingScheduler` and `SwtScheduler` from the library, at this point.

Can you clarify what is your usage? You can also chime in #273 I just opened.

**Comment by vogella** [comment]
A have a client using the SWTScheduler but we copied the scheduler over to our code base to compile against the right SWT libraries, so removal in this project would be fine for us.
