### ISSUE TITLE
Deprecating reactor-extra's Swing/SwtScheduler (removal in 3.6.0)

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-addons#273]
### Motivation
The `SwingScheduler` and `SwtScheduler` adapters don't seem to have much traction, as far as we're aware.
The SWT one is using outdated SWT libraries and complexifies the build infrastructure for little gain.

(for instance, searching for `reactor.swing.SwingScheduler` results in 2 code hits in all of GitHub. The other one gets 3 hits total...)

### Deprecation and removal plan
1. Deprecation in 3.4.7 (estimated early March 2022)
2. Removal in 3.6.0 (no planned date, probably late 2023 or late 2024)
~2. Removal in 3.5.0 (estimated last quarter of 2022)~ (see comment below)

### Additional steps
 - [ ] Remove from reference guide appendix in core (this seems to be the main source of results when searching for `SwtScheduler` in all of GitHub btw) => https://github.com/reactor/reactor-core/pull/2959
 - [ ] Deprecate in parallel the corresponding extensions in `reactor-kotlin-extensions` => reactor/reactor-kotlin-extensions#38
 - [ ] Earlier removal of the very simple extension in `reactor-kotlin-extensions` 1.2.0 (see also reactor/reactor-kotlin-extensions#38)

**Comment by vogella** [comment]
A have a client using the SWTScheduler but we copied the scheduler over to our code base to compile against the right SWT libraries, so removal in this project would be fine for us.

**Comment by simonbasle** [comment]
Note: despite the low criticality of these adapters, we might want to avoid making any exceptions to our deprecation policy, so technically this would be removable in 3.6.0 at the earliest (and we definitely won't keep it past that).
