### ISSUE TITLE
[Open Discussion] general feedback

### ISSUE THREAD

**Issue by aalmiray** [reactor/reactor-addons#28]
Encouraged by https://twitter.com/projectreactor/status/788678127606173696 I'd like to start an open discussion as an outsider to the project that's interested in using the proposed API. 
1. Like @smaldini my background is rotted in the Groovy community so I was a bit confused when I sa the name for `ScriptedSubscriber`. I though it was related to scripting capabilities (Groovy, BSF, JSR-223, etc).
2. Per https://github.com/reactor/reactor-addons/blob/master/reactor-test/src/test/java/reactor/test/subscriber/ScriptedSubscriberIntegrationTests.java#L134-L142 the usage of `@Test(expected = AssertionError.class)` is to coarse IMHO. We're expecting a test to fail, so it can fail for any reason, not necessarily because of the intended reason. The linked testcase may fail because the developer added more `expectedValue()` calls, changed `expectedValue('foo')` to `expectedValue('bar')`, or simply by adding `assertTrue(false)` at the top of the test method.
3. I'd like to see additional `expect` methods that take Hamcrest `Matcher` as argument.
4. Would it make sense to rename `verify` to `verifyOn` ?
5. Would it make sense to turn around the start/termination methods (`create` and `verify`) such that the script reads as follows:
   
   ScriptedSubscriber.subscribeOn(flux)
                                  .expectValue("foo")
                                  .expecteComplete()
                                  .verify();

Or is it the intention that a "script" may be applied to multiple observable sources? If so then `verify(src)` makes more sense.

**Comment by simonbasle** [comment]
hey @aalmiray 👋 

my pov on your questions:

1. I can see where the confusion comes from :) The idea of `ScriptedSubscriber` is that it verifies a prepared "script" or "scenario", hence the name.
2. I agree, we should probably rework and make those tests finer grained. Still work in progress 🔜 
3. Interesting idea. Not sure we want to add Hamcrest as a transitive dependency though... Note that nothing prevents you from using hamcrest (or assertJ for that mater) in a `consumeNextWith()` call (takes a `Consumer<T>` and reacts to `AssertionError` correctly)
 4. I don't think so, it would be too close to `publishOn`/`subscribeOn` from reactor, which have different semantics.
 5. A script should normally not be applied to multiple publishers, unless you want to verify that it is just cancelled when applied to a second publisher... so yeah it would make sense to provide the `Flux` at the beginning. Probably in the factory method (`create`). Note that it could pave the way to a specialized factory method that deals with `VirtualTimeScheduler` on your behalf...

**Comment by smaldini** [comment]
I've reworked a bit the API for building in #31 - Mainly in addition to building a Subscriber itself, we have an encapsulated super interface (Verifier) that can control time and replay verification on verify. 
```
Verifier.with(() -> Flux.just("foo", "bar", "foobar")
		                        .delay(Duration.ofHours(1))
		                        .log())
		        .thenAwait(Duration.ofHours(1))
		        .expectNext("foo")
		        .thenAwait(Duration.ofHours(`1))
		        .expectNext("bar")
		        .thenAwait(Duration.ofHours(1))
		        .expectNext("foobar")
		        .expectComplete()
		        .verify();```

**Comment by simonbasle** [comment]
I think most of your questions have been covered @aalmiray, and the API has seen some improvement since then (now based around `StepVerifier`).

The only dangling point is the expect method with matchers. We've discussed that internally and we think that it would add a strong dependency to specific test libraries which we don't think is a good thing. Users could be willing to use testng as a testing library for instance, or their other favorite assertion library (eg. AssertJ). These can change overtime, etc... Also, often you will want to assert several properties of a value, not just the value itself. In which case just having the `Matcher` won't cut it.

The fact that `AssertionError`s are caught and handled correctly is sufficient IMHO, and you can use whatever assertion library you want with `thenConsumeWith(Consumer<T>)`.

Closing this issue for now, don't hesitate to reopen if you have more general feedback, or open new issues if you have specific suggestions 👍

**Comment by aalmiray** [comment]
Agreed. Thanks for all the updates. I regret that `Hamcrest` could not be added at this point but I understand the reasoning. Also, though `thenConsumeWith(Consumer<T>)` serves as an entry point to writing custom assertions as you suggest the name does not convey that behavior. Given that `StepVerifier` was designed for testing in mind, wouldn't it make more sense to rename the method to point out that's where custom assertions may be made? 😏
