### ISSUE TITLE
Consumer Callbacks (v1 to v2 differences)

### ISSUE THREAD

**Issue by connollyst** [reactor/reactor-addons#5]
In Reactor v1.x we had a nice [notify with a callback function](https://github.com/reactor/reactor/blob/1.1.x/reactor-core/src/main/java/reactor/core/Reactor.java#L238) which has been removed in v2.x. I'm sure there's a reason for this, however, as someone migrating to v2 I found myself lost.

Here's a unit test Gist to show what I tried, what works, and what doesn't:
https://gist.github.com/connollyst/da63998f65c309a442d8228ef61f7453

The gist of the gist..

    // In reactor v1.x, we used to have..
    reactor.notify("say.hi", Event.wrap("Hello World!"), call::back);

    // In reactor v2.x it's gone, we have something similar in..
    bus.sendAndReceive("say.hi", Event.wrap("Hello World!"), call::back);
    // .. but this only works if my callback is set up with bus.receive, mine is bus.on

    // events have a 'replyTo', lets try that..
    bus.on($("callback"), call::back);
    bus.notify("say.hi", Event.wrap("Hello World!", "callback"));
    // .. nope, doesn't get called

Any thoughts?

**Comment by smaldini** [comment]
Moved to http://github.com/reactor/reactor-bus
