### ISSUE TITLE
prevent expectNextCount/expectNextSequence to consider values asserted by other expectXXX

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-addons#52]
right now, the following test succeeds:

```java
@Test
public void expectNextCount2elements() {
	Flux<String> flux = Flux.just("foo", "bar");
	StepVerifier.create(flux)
	            .expectNext("foo", "bar")
	            .expectNextCount(2)
	            .verifyComplete();
}
```

It means that the `expectNextCount` counts the "foo" and "bar" values asserted by `expectNext`.

But the following test fails:
```java
@Test
public void expectNextCount4elements() {
	Flux<String> flux = Flux.just("foo", "bar", "foz", "baz");
	StepVerifier.create(flux)
	            .expectNext("foo", "bar")
	            .expectNextCount(2)
	            .verifyComplete();
}
```

My gut feeling is that the inverse should be true: `expectNextCount` could then be used in conjunction with `expectNext` (or other onNext expectations) in order to "skip" over an amount of onNext notifications, eg. asserting the first 5 elements and last element in a sequence of 20 elements in details, but only care about the number of elements in the middle:

```java
@Test
public void expectNextCountRange() {
    Flux<Integer> flux = Flux.range(1, 20);
    StepVerifier.create(flux)
                .expectNext(1, 2, 3, 4, 5) //<- assert first five
                .expectNextCount(14) //<- only care that elements 6-19 are there
                .expectNext(20) //<- assert last element
                .verifyComplete();
}
```

**Comment by simonbasle** [comment]
the use of the `produced` field should also probably be double-checked, notably in how it makes `expectNextCount` and `checkRequestOverflow` interact.

**Comment by sdeleuze** [comment]
`StepVerifier` principle clearly define sequential steps, so I do think that `expectNextCount4elements()`  should succeed while `expectNextCount2elements()` should fail. I am very surprised by the current behavior you described.

**Comment by simonbasle** [comment]
`expectNextSequence` also has a behavior problem in multi-steps scenarios, as the following fails:

```java
@Test
public void expectNextSequenceIncomplete() {
	Flux<String> flux = Flux.just("foo", "bar", "baz");
	StepVerifier.create(flux)
	            .expectNextSequence(Arrays.asList("foo", "bar"))
	            .expectNext("baz")
	            .verifyComplete();
}
```

Similarly to the above, it should work in tandem with expectNext to only assert the first 2 elements in the sequence and, once the iterable is depleted, let subsequent steps in the scenario execute.
