### ISSUE TITLE
StepVerifier#withVirtualTime(Supplier) stucks

### ISSUE THREAD

**Issue by apischan** [reactor/reactor-addons#61]
I started to learn reactor with [this](https://github.com/reactor/lite-rx-api-hands-on/).
Here I stuck with `StepVerifier` tests. So in this example I modified the original test a bit just to make it quicker.
```
@Test
public void countWithVirtualTime() {
    expect3600Elements(() -> Flux.interval(Duration.ofMills(1)).take(5));
}

void expect3600Elements(Supplier<Flux<Long>> supplier) {
    StepVerifier.withVirtualTime(supplier)
                .expectNextCount(5)
                .expectComplete()
                .verify();
}
```
Maybe I'm doing something wrong here but it goes to infinite loop in `DefaultVerifySubscriber#pollTaskEventOrComplete`.

The analogous test just works fine:
```
@Test
public void count() {
    stepVerifierTesting.expect10Elements(Flux.interval(Duration.ofSeconds(1)).take(10));
}

void expect10Elements(Flux<Long> flux) {
    StepVerifier.create(flux)
                .expectNextCount(10)
                .expectComplete()
                .verify();
}
```
Maybe I misunderstood `StepVerifier#withVirtualTime` but it looks the issue for me.

**Comment by smaldini** [comment]
In virtual time you have to avance the clock yourself in your test script before or after an expect use thenAwait(Duration) and that will instruct the virtual time scheduler to Advance Time for the same period, triggering your expectations. However we could automatically advance time for an infinite period automatically in verify(), that could be an interesting user experience improvement in case you forget thenAwait.

**Comment by apischan** [comment]
@smaldini so is there any plan to implement some improvement if someone forget or don't know about thenAwait? Or we can close this issue?
