### ISSUE TITLE
Non relevant error message with consumeNextWith()

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-addons#64]
With the following test:

```
StepVerifier.create(response.flatMap{ r -> r.bodyToFlux(Event::class)})
                    .consumeNextWith { assertEquals(2012, it.year) }
                    .consumeNextWith { assertEquals(2013, it.year) }
                    .consumeNextWith { assertEquals(2014, it.year) }
                    .consumeNextWith { assertEquals(2015, it.year) }
                    .consumeNextWith { assertEquals(2016, it.year) }
                    .consumeNextWith { assertEquals(2017, it.year) }
                    .expectComplete()
                    .verify()
```

I get the following not very useful error message:

```
Expectation failed (failed running expectation on signal [onNext(FluxError)] with [java.lang.ClassCastException]:
reactor.core.publisher.FluxError cannot be cast to mixit.model.sponsor.Event)
java.lang.AssertionError: expectation failed (failed running expectation on signal [onNext(FluxError)] with [java.lang.ClassCastException]:
reactor.core.publisher.FluxError cannot be cast to mixit.model.sponsor.Event)
	at reactor.test.DefaultStepVerifierBuilder.failPrefix(DefaultStepVerifierBuilder.java:1679)
	at reactor.test.DefaultStepVerifierBuilder.fail(DefaultStepVerifierBuilder.java:1675)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1017)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onNext(DefaultStepVerifierBuilder.java:764)
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:191)
```

It would expect the message + stacktrace of the error instead of this class cast error.

**Comment by simonbasle** [comment]
@sdeleuze could you try to find the root cause of the `ClassCastException`? What seems fishy and makes me think the problem is outside of StepVerifier is that `onNext(FluxError)` (which is the implementation class behind `Flux.error`).

**Comment by sdeleuze** [comment]
Oh, indeed it may come from `bodyToFlux(Event::class)`  sorry.

**Comment by sdeleuze** [comment]
Ok, I am back on that and I confirm with confidence that there is a real and **VERY** nasty bug to fix. The real exception is hidden behind an unrelated `ClassCastException` coming from Reactor because of [this line](https://github.com/reactor/reactor-addons/blob/master/reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java#L978).

In my use case, I have the following test:

```kotlin
 StepVerifier.create(webClient
                    .getJson("http://localhost:${subject.port}/api/session/2421")
                    .flatMap { r -> r.bodyToFlux(Session::class) })
                    .consumeNextWith {
                        assertEquals("Selling BDD to the Business", it.title)
                        assertEquals("NORTH", it.speakers.iterator().next().lastname)
                    }
                    .verifyComplete()
```

I have debug the code and ` r.bodyToFlux(Session::class)` returns the nice and expressive `MissingKotlinParameterException` I would like to get at `StepVerifier` level. But at [this line](https://github.com/reactor/reactor-addons/blob/master/reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java#L978) Reactor throw a `ClassCastException` because `boolean onSignal(Signal<T> actualSignal)` signature require the signal to be of type `Session` but it is a `MissingKotlinParameterException`.

I am not sure how to fix this, but with something like relaxing the signature to handle `Signal<?>` to avoid throwing a `ClassCastException` when the signal is an error one.

**Comment by sdeleuze** [comment]
I close this issue definitively since as found by @simonbasle, the root cause of this issue if in `Jackson2JsonDecoder` which returns a `Flux.error()` within a map operation, at 
https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/codec/json/Jackson2JsonDecoder.java#L121.

I will fix this issue on Spring Framwork side, sorry for the noise ;-)
