### ISSUE TITLE
What happened to reactor-alloc?

### ISSUE THREAD

**Issue by IceMan81** [reactor/reactor-addons#8]
I came here looking for reactor-alloc as the main reactor project lists reactor-alloc under reactor-addons. I was going to ask about a RingBuffer based lock-free implementation of an allocator (for object pooling) but was surprised to see that reactor-alloc doesn't exist. 

My interest in a lock-free allocator is related to my discussion here
https://groups.google.com/d/msg/reactor-framework/h2Dsm0USZjw/bGNotRyNCQAJ

If its not possible to avoid object creation when using reactor based messaging, then a lock free allocator would be useful to mitigate GC issues.

**Comment by smaldini** [comment]
We have currently progressed in various ways on reactor-core, where we avoid event creation by directly and statically typing the user payload.

**Comment by IceMan81** [comment]
@smaldini Even though the the event is statically typed, the event value is passed by reference. So in many instances the publishers always end up creating a value object for every publish which adds GC pressure for hot streams. What would help is a way to set the value in the event i.e. reuse the value objects in addition to reusing the event objects. 

Thoughts?
