### ISSUE TITLE
Implement a new reactor-math addon to support math operations

### ISSUE THREAD

**Issue by rajinisivaram** [reactor/reactor-addons#83]
Add a reactor-math extension that supports mathematical operations like sum, average, max, min etc. A similar extension is already available for RxJava2.

**Comment by smaldini** [comment]
Note that https://github.com/reactor/reactive-streams-commons as similar operators as well but @akarnokd can tell they might be out of date.

**Comment by akarnokd** [comment]
The tools have been moved around but the basic pattern is the same. Also see [RxJava2Extensions Math](https://github.com/akarnokd/RxJava2Extensions/tree/master/src/main/java/hu/akarnokd/rxjava2/math) that is guaranteed up-to-date algorithmically.

**Comment by akarnokd** [comment]
If you plan to add an instance `Flux.sum()`, you may want to consider a mapping variant instead of a forced-cast variant:

```java
public final Flux<Integer> sum(Function<? super T, ? extends Number> f);
```

That allows identity mapping if `T extends Number` by itself and otherwise ensures type-safety and no runtime `ClassCastException`.
