### ISSUE TITLE
Question: When to expect reactor-bus release 3?

### ISSUE THREAD

**Issue by jangalinski** [reactor/reactor-addons#9]
I am waiting for the bus release to adopt my project. Although core is out for some weeks now, bus is still snapshot. What are your plans?

**Comment by bobwenx** [comment]
same here, when to expect `reactor-logback` release 3.xx?

**Comment by beihaifeiwu** [comment]
+1

**Comment by smaldini** [comment]
Moved to http://github.com/reactor/reactor-bus
