### ISSUE TITLE
AsyncAppender does not stop properly

### ISSUE THREAD

**Issue by jacek-lewandowski** [reactor/reactor-addons#91]
I noticed that `AsyncAppender` does not drain buffered events when stopping and it does not stop the underlying appender.

I'm not very familiar with the code here, but it looks like `AsyncAppender.stop()` should call `processor.awaitAndShutdown` to stop accepting new events and drain the buffer, and then it should stop underlying appender.

It seems like `AsyncAppender.onComplete()` is never called (or at least it isn't called sometimes).

**Comment by smaldini** [comment]
Have added a tweak to stop it on all detach but I'm not sure it is exactly what you face, could you provide a sample ?

https://github.com/reactor/reactor-addons/commit/04e7d93f4b848c8bf8f52af63dbb3e266f279c50

**Comment by smaldini** [comment]
Closing for now - waiting for feedback
