### ISSUE TITLE
Rename reactor-math to reactor-extra

### ISSUE THREAD

**Issue by rajinisivaram** [reactor/reactor-addons#93]
Rename `reactor-math` to `reactor-extra` since `math` is a very small set of methods to stand on its own and `extra` can hold other extensions like routing etc.

**Comment by simonbasle** [comment]
The goal is to add operators and stuff that we don't think makes sense for 100% of `reactor-core` users, but is useful for users who are willing to pay the price of a slightly larger surface API / additional jar. It could serve as an incubator for additional operators as well.
